package Observer::Model::ATAS;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Observer::SchemaATAS',
);

=head1 NAME

Observer::Model::ATAS - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Observer>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Observer::SchemaATAS>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.6

=head1 AUTHOR

A clever guy

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
